# Metadata
site_name: pgtoolkit documentation
site_description: Postgres format library
site_author: Dalibo Labs
copyright: © Dalibo 2018
repo_name: pgtoolkit
repo_url: https://github.com/dalibo/pgtoolkit

pages:
- Home: index.md

theme: readthedocs
site_dir: build/docs/

# Markdown settings
markdown_extensions:
- admonition
- fenced_code
- headerid
- sane_lists
- smarty
- toc:
    baselevel: 2
    permalink: yes
- wikilinks
