#!/bin/bash -eux

teardown() {
    exit_code=$?
    # If not on CI, wait for user interrupt on exit
    if [ -z "${CI-}" -a $exit_code -gt 0 -a $$ = 1 ] ; then
        tail -f /dev/null
    fi
}

trap teardown EXIT TERM

top_srcdir=$(readlink -m $0/../..)
cd $top_srcdir
test -f setup.py

yum_install() {
    local packages=$*
    sudo yum install -y $packages
    rpm --query --queryformat= $packages
}

# Fasten yum by disabling updates repository
if [ -f /etc/yum.repos.d/CentOS-Base.repo ] ; then
    sudo sed -i '/^\[updates\]/,/^gpgkey=/d' /etc/yum.repos.d/CentOS-Base.repo
fi

# Purge previous installation
if rpm --query --queryformat= python3-pgtoolkit ; then
    sudo yum remove -y python3-pgtoolkit
fi

rm -rf build/bdist*/rpm

yum_install python39 python39-setuptools

# Set default python3 to python3.9
update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1

# Build it

sudo sed -i 's/\.centos//' /etc/rpm/macros.dist

rpmbuild -bb \
         --undefine _disable_source_fetch \
         --define "_topdir ${top_srcdir}/dist" \
         --define "_sourcedir ${top_srcdir}/dist" \
         --define "_rpmdir ${top_srcdir}/dist" \
         rpm/python-pgtoolkit.spec
version=$(sed -n '/^Version:/{s,.*:\t,,g; p; q}' rpm/python-pgtoolkit.spec)
rpm=dist/noarch/python3-pgtoolkit*${version}*$(rpm --eval '%dist').noarch.rpm
ln -fs noarch/$(basename $rpm) dist/last_build.rpm

chown -R $(id -nu):$(id -ng) dist

# Test it
sudo yum install -y $rpm
cd /
python3 -c 'import pgtoolkit'
