#!/bin/bash -eux

teardown() {
    exit_code=$?
    # If not on CI, wait for user interrupt on exit
    if [ -z "${CI-}" -a $exit_code -gt 0 -a $$ = 1 ] ; then
        tail -f /dev/null
    fi
}

trap teardown EXIT TERM

top_srcdir=$(readlink -m $0/../..)
cd $top_srcdir
test -f setup.py

yum_install() {
    local packages=$*
    sudo yum install -y $packages
    rpm --query --queryformat= $packages
}

# Fasten yum by disabling updates repository
if [ -f /etc/yum.repos.d/CentOS-Base.repo ] ; then
    sudo sed -i '/^\[updates\]/,/^gpgkey=/d' /etc/yum.repos.d/CentOS-Base.repo
fi

# Purge previous installation
if rpm --query --queryformat= python3-pgtoolkit ; then
    sudo yum remove -y python3-pgtoolkit
fi

rm -rf build/bdist*/rpm

# install python 3.6 on CentOS 8
if rpm --eval "%{dist}" | grep -q 'el8'; then
    yum_install python36 python3-setuptools
else
    yum_install python3 python3-setuptools
fi

# Build it
# No --undefine on CentOS 6.
if ! rpmbuild --version | grep -q '4.8' ; then
        rpmbuild_args="--undefine _disable_source_fetch"
fi

sudo sed -i 's/\.centos//' /etc/rpm/macros.dist

rpmbuild -bb \
         ${rpmbuild_args-} \
         --define "_topdir ${top_srcdir}/dist" \
         --define "_sourcedir ${top_srcdir}/dist" \
         --define "_rpmdir ${top_srcdir}/dist" \
         rpm/python-pgtoolkit.spec
version=$(sed -n '/^Version:/{s,.*:\t,,g; p; q}' rpm/python-pgtoolkit.spec)
rpm=dist/noarch/python3-pgtoolkit*${version}*$(rpm --eval '%dist').noarch.rpm
ln -fs noarch/$(basename $rpm) dist/last_build.rpm

chown -R $(id -nu):$(id -ng) dist

# Test it
sudo yum install -y $rpm
cd /
python3 -c 'import pgtoolkit'
