#!/bin/bash -eux

teardown() {
    exit_code=$?
    # If not on CI, wait for user interrupt on exit
    if [ -z "${CI-}" -a $exit_code -gt 0 -a $$ = 1 ] ; then
        tail -f /dev/null
    fi
}

trap teardown EXIT TERM

top_srcdir=$(readlink -m $0/../..)
cd $top_srcdir
test -f setup.py

yum_install() {
    local packages=$*
    sudo yum install -y $packages
    rpm --query --queryformat= $packages
}

# Fasten yum by disabling updates repository
sudo sed -i '/^\[updates\]/,/^gpgkey=/d' /etc/yum.repos.d/CentOS-Base.repo

# Purge previous installation
if rpm --query --queryformat= python-pgtoolkit ; then
    sudo yum remove -y python-pgtoolkit
fi

rm -rf build/bdist*/rpm

# Build it
# No --undefine on CentOS 6.
if ! rpmbuild --version | grep -q '4.8' ; then
        rpmbuild_args="--undefine _disable_source_fetch"
fi

rpmbuild -ba \
         ${rpmbuild_args-} \
         --define "_topdir ${top_srcdir}/dist" \
         --define "_sourcedir ${top_srcdir}/dist" \
         rpm/python-pgtoolkit.spec
version=$(sed -n '/^Version:/{s,.*:\t,,g; p; q}' rpm/python-pgtoolkit.spec)

# Test it
sudo yum install -y dist/noarch/python-pgtoolkit*${version}*$(rpm --eval '%dist').noarch.rpm
cd /
python -c 'import pgtoolkit'
