version: 2.1

jobs:
  rpm-centos7:
    working_directory: ~/workspace
    docker: [{image: "rpmbuild/centos7"}]
    steps:
    - checkout
    - run: rpm/build
    - persist_to_workspace:
        root: ~/workspace
        paths: ["dist/"]
    - store_artifacts:
        path: ~/workspace/dist/

  rpm-centos8:
    working_directory: ~/workspace
    docker: [{image: "dalibo/labs-sdk:centos8"}]
    steps:
    - checkout
    - run: rpm/build
    - persist_to_workspace:
        root: ~/workspace
        paths: ["dist/"]
    - store_artifacts:
        path: ~/workspace/dist/

  deb-buster:
    docker:
      - image: debian:buster
    steps:
      - checkout
      - run: |
          apt-get update -qq
          apt-get install -qq devscripts equivs
          apt-get -qq build-dep .
      - run: |
          python3 setup.py sdist
          version=$(python3 setup.py --version)
          mk-origtargz dist/pgtoolkit-$version.tar.gz
      - run: dpkg-buildpackage
      - run: debc

workflows:
  version: 2
  pipeline:
    jobs:
    - rpm-centos7
    - rpm-centos8
    - deb-buster
