version: 2

jobs:
  unit-py36:
    docker:
    - image: python:3.6
      environment:
        TERM: linux
        TERMINFO: /etc/terminfo
    working_directory: /workspace
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - pgtoolkit-{{ .Branch }}
            - pgtoolkit-master
      - run: &deps
          name: Install dependencies
          command: |
            pip install --upgrade --requirement requirements-ci.txt --editable .
      - save_cache: &save_cache
          key: pgtoolkit-{{ .Branch }}
          paths:
            - "~/.cache/pip/"
      - run:
          name: Lint check
          command: |
            git diff --check $(git merge-base origin/master $CIRCLE_SHA1)..$CIRCLE_SHA1
            flake8 .
      - run: &unit_tests
          name: Unit tests
          command: |
            pytest tests/
            codecov
      - run:
          name: Check documentation
          command: |
            python setup.py --long-description | rst2html.py --strict >/dev/null
            mkdocs build --clean --strict
      - run: &script_tests
          name: Script tests
          command: |
            tests/datatests.sh

  unit-py26:
    docker:
    - image: dalibo/python26:slim
      environment:
        TERM: linux
        TERMINFO: /etc/terminfo
    working_directory: /workspace
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: *deps
      - save_cache: *save_cache
      - run: *unit_tests
      - run: *script_tests

workflows:
  version: 2
  pipeline:
    jobs:
    - unit-py36
    - unit-py26
