version: 2.1

jobs:
  rpm-centos7:
    working_directory: ~/workspace
    docker: [{image: "rpmbuild/centos7"}]
    steps:
    - checkout
    - run: rpm/build
    - persist_to_workspace:
        root: ~/workspace
        paths: ["dist/"]
    - store_artifacts:
        path: ~/workspace/dist/

  rpm-centos8:
    working_directory: ~/workspace
    docker: [{image: "dalibo/labs-sdk:centos8"}]
    steps:
    - checkout
    - run: rpm/build
    - persist_to_workspace:
        root: ~/workspace
        paths: ["dist/"]
    - store_artifacts:
        path: ~/workspace/dist/

  unit-py36:
    docker:
    - image: python:3.6
      environment:
        TERM: linux
        TERMINFO: /etc/terminfo
    working_directory: /workspace
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - pgtoolkit-{{ .Branch }}
            - pgtoolkit-master
      - run: &deps
          name: Install dependencies
          command: |
            pip install --upgrade --requirement requirements-ci.txt --editable .
      - save_cache: &save_cache
          key: pgtoolkit-{{ .Branch }}
          paths:
            - "~/.cache/pip/"
      - run:
          name: Lint check
          command: |
            git diff --check $(git merge-base origin/master $CIRCLE_SHA1)..$CIRCLE_SHA1
            flake8 .
            black --check --diff .
      - run:
          name: Type check
          command: |
            mypy --strict pgtoolkit
      - run: &unit_tests
          name: Unit tests
          command: |
            pytest pgtoolkit/ tests/
            codecov -F ${CIRCLE_JOB/unit-/}
      - run:
          name: Check documentation
          command: |
            python setup.py --long-description | rst2html.py --strict >/dev/null
            make -C docs clean html
      - run: &script_tests
          name: Script tests
          command: |
            tests/datatests.sh

workflows:
  version: 2
  pipeline:
    jobs:
    - unit-py36
    - rpm-centos7
    - rpm-centos8
