version: 2

jobs:
  unit-py36:
    docker:
    - image: python:3.6
      environment:
        TERM: linux
        TERMINFO: /etc/terminfo
    working_directory: /workspace
    steps:
      - checkout
      - restore_cache:
          keys:
            - pgtoolkit-{{ .Branch }}
            - pgtoolkit-master
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade --requirement requirements-ci.txt --editable .
      - save_cache:
          key: pgtoolkit-{{ .Branch }}
          paths:
            - "~/.cache/pip/"
      - run:
          name: Lint check
          command: |
            git diff --check $(git merge-base origin/master $CIRCLE_SHA1)..$CIRCLE_SHA1
            flake8 .
      - run:
          name: Unit tests
          command: |
            pytest tests/
            codecov
      - run:
          name: Check documentation
          command: |
            python setup.py --long-description | rst2html.py --strict >/dev/null
            mkdocs build --clean --strict
      - run:
          name: Script tests
          command: |
            tests/datatests.sh

workflows:
  version: 2
  pipeline:
    jobs:
    - unit-py36
