version: 2

jobs:
  unit-py36:
    docker:
    - image: python:3.6
      environment:
        TERM: linux
        TERMINFO: /etc/terminfo
    working_directory: /workspace
    steps:
      - checkout
      - restore_cache:
          keys:
            - pgtoolkit-{{ .Branch }}
            - pgtoolkit-master
      - run:
          name: Python lint and tests
          command: |
            set -x
            pip install --upgrade --requirement requirements-ci.txt --editable .
            git diff --check $(git merge-base origin/master $CIRCLE_SHA1)..$CIRCLE_SHA1
            flake8 .
            pytest tests/
            codecov
      - save_cache:
          key: pgtoolkit-{{ .Branch }}
          paths:
            - "~/.cache/pip/"

workflows:
  version: 2
  pipeline:
    jobs:
    - unit-py36
