name: Documentation

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: python -m pip install -e ".[doc]"
      - name: Check documentation
        run: |
          rst2html --strict README.rst > /dev/null
          make -C docs clean html
