name: Documentation

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: python -m pip install -r requirements-ci.txt -e .
      - name: Check documentation
        run: |
          python setup.py --long-description | rst2html.py --strict >/dev/null
          make -C docs clean html
