name: Documentation

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: python -m pip install -r requirements-ci.txt -e .
      - name: Check documentation
        run: |
          python setup.py --long-description | rst2html --strict >/dev/null
          make -C docs clean html
