name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: python -m pip install flake8 black check-manifest isort mypy
      - name: Style
        run: |
          flake8 .
          black --check --diff .
          check-manifest .
          isort --check --diff .
      - name: Typing
        run: mypy --strict pgtoolkit
