name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          fetch-tags: true
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install
        run: python -m pip install setuptools wheel twine
      - name: Build
        run: |
          python setup.py check
          python setup.py sdist bdist_wheel
          python -m twine check dist/*
      - name: Publish
        run: python -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
